series: Intermediate C++
title: Friend
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: The friend keyword allows private members to be accessed by specific other functions and classes.
language: C++
tags:
  - Core
extra_resources:
  - link: http://www.cplusplus.com/doc/tutorial/inheritance/
    title: Source
connections:
  - series: Basic C++
    title: Virtual Functions
  - series: Basic C++
    title: References